# Generated by Django 4.0 on 2021-12-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_post_updated_at_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='shopping/images/%Y/%m/%d/'),
        ),
    ]
