# Generated by Django 3.2.6 on 2021-12-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='list_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
