# Generated by Django 3.2.6 on 2021-12-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_post_list_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hook_text',
            new_name='price_text',
        ),
    ]
