# Generated by Django 3.2.6 on 2021-12-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_rename_hook_text_post_price_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='produce_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='price_text',
            field=models.CharField(max_length=50),
        ),
    ]
