# Generated by Django 3.2.6 on 2021-12-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_auto_20211220_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='list_text',
            new_name='kcal_text',
        ),
        migrations.AddField(
            model_name='post',
            name='capacity_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
